name: Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: "0.157.0"
      HUGO_CACHEDIR: /tmp/hugo_cache_runner
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Disable git quotePath
        run: git config core.quotePath false

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true

      - name: Setup Cache
        uses: actions/cache@v5
        with:
          path: ${{ env.HUGO_CACHEDIR }}
          key: ${{ runner.os }}-hugo${{ env.HUGO_VERSION }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugo${{ env.HUGO_VERSION }}-

      - name: Build with hugo
        run: hugo --minify --gc
        env:
          HUGO_ENV: production
          HUGO_ENVIRONMENT: production

      - name: Debug hugo info
        run: hugo config && hugo version

      - name: Precompress with zstd
        run: chmod +x ./zstd.sh && ./zstd.sh

      - name: Deploy via rsync
        uses: easingthemes/ssh-deploy@main
        with:
          ARGS: -az --delete --no-perms --compress-choice=lz4
          SOURCE: public/
          TARGET: /var/www/blog
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
